// This file was auto-generated by Fern from our API Definition.

package api

type LoginOauthRequest struct {
	// Your OAuth Provider ID
	Provider string `json:"-"`
	// Will be passed through your lookup URL to get the user ID. Required if no `code`.
	AccessToken *string `json:"-"`
	// Will be passed to the OAuth token endpoint to get a token. Required if no `accessToken`.
	Code *string `json:"-"`
	// Override where the user will navigate to after successfully logging in.
	Redirect *string `json:"-"`
	// If an error happens, redirects the user to this url, with at least query parameters `code`, `errorName` and `message`.
	ErrorRedirect *string `json:"-"`
}
