// This file was auto-generated by Fern from our API Definition.

package api

// Subset of properties listed here
type ClanResponse struct {
	Id          *ObjectIdString  `json:"_id,omitempty"`
	Name        *string          `json:"name,omitempty"`
	DisplayName *string          `json:"displayName,omitempty"`
	Members     []ObjectIdString `json:"members,omitempty"`
	OwnerId     *ObjectIdString  `json:"ownerID,omitempty"`
	Description *string          `json:"description,omitempty"`
	Type        *string          `json:"type,omitempty"`
	Kind        *string          `json:"kind,omitempty"`
	Metadata    map[string]any   `json:"metadata,omitempty"`
}

type ClansUpsertMemberRequest struct {
	// The `_id` or `slug` of the user to add to the clan.
	UserId string `json:"userId"`
}
