// This file was auto-generated by Fern from our API Definition.

package api

type StatsGetPlaytimeStatsRequest struct {
	// Earliest an included user was created
	StartDate *string `json:"-"`
	// Latest an included user was created
	EndDate *string `json:"-"`
	// Filter by country string
	Country *string `json:"-"`
}

type LicenseStatsResponse struct {
	// Total number of license days granted
	LicenseDaysGranted *float64 `json:"licenseDaysGranted,omitempty"`
	// Number of license days used
	LicenseDaysUsed *float64 `json:"licenseDaysUsed,omitempty"`
	// Number of license days remaining
	LicenseDaysRemaining *float64 `json:"licenseDaysRemaining,omitempty"`
	// Number of active/valid licenses
	ActiveLicenses *float64 `json:"activeLicenses,omitempty"`
}

type PlaytimeStatsResponse struct {
	// Total play time in seconds
	PlayTime *float64 `json:"playTime,omitempty"`
	// Number of levels played
	GamesPlayed *float64 `json:"gamesPlayed,omitempty"`
}
